```{r}
library(ape)
library(magrittr)
library(ggplot2)
library(treeImbalance)
```

I load in the clock-like trees generated by LSD.

```{r}
lsd.dirs <- list.dirs("../lsd")
lsd.dirs <- lsd.dirs[2:length(lsd.dirs)]
stubs <- strsplit(lsd.dirs,"/") %>% lapply(.,"[",3) %>% unlist
trees.fn <- paste(lsd.dirs,"/",stubs,"_result_newick_date.txt",sep="")
numtrees <- length(trees.fn)
trees <- list()
for(i in 1:numtrees){
  trees[[i]] <- read.tree(trees.fn[i])
}
```

```{r}
globalstat <- function(s){
  tail(s[[2]],1)
}
```

```{r}
nsims <- 100
s.vec <- rep(0,numtrees)
ch.vec <- rep(0,numtrees)
snull.list <- list()
chnull.list <- list()
for(i in 1:numtrees){
  print(paste(i,"/",numtrees))
  tr <- trees[[i]]
  s <- snt(tr)
  ch <- ct(tr)
  tr.s <- globalstat(s)
  tr.ch <- globalstat(ch)
  s.vec[i] <- tr.s
  ch.vec[i] <- tr.ch
  snull <- rep(0,nsims)
  chnull <- rep(0,nsims)
  for(j in 1:nsims){
    trp <- getSimTree(tr)
    sp <- snt(trp)
    chp <- ct(trp)
    snull[j] <- globalstat(sp)
    chnull[j] <- globalstat(chp)
  }
  snull.list[[i]] <- snull
  chnull.list[[i]] <- chnull
}
```

```{r}
svg("sackins_lsd.svg",width=9,height=15)
par(mfrow=c(5,3))
for(i in 1:15){
  alls <- c(snull.list[[i]],s.vec[i])
  hist(snull.list[[i]],breaks=100,xlim=c(min(alls),max(alls)),main=stubs[i],xlab="Sackin's index")
  abline(v=s.vec[i],col="red")
}
dev.off()
```


```{r}
svg("cherries_lsd.svg",width=9,height=15)
par(mfrow=c(5,3))
for(i in 1:15){
  allch <- c(chnull.list[[i]],ch.vec[i])
  hist(chnull.list[[i]],breaks=100,xlim=c(min(allch),max(allch)),main=stubs[i],xlab="Cherries")
  abline(v=ch.vec[i],col="red")
}
dev.off()
```