```{r}
library(ape)
library(magrittr)
```


```{r}
phyml.gtr <- function(runid,output.file,file.name){
phyxml <- sprintf('
<phyml runid="%s" output.file="%s">

  <topology>
    <instance id="T1" init.tree="bionj" optimise.tree="yes" search="spr"/>
  </topology>

  <branchlengths id="BL1">
    <instance id="L1" optimise.lens="yes"/>
  </branchlengths>

  <ratematrices id="RM1">
    <instance id="M1" model="GTR" optimise.rr="yes"/>
  </ratematrices>

  <equfreqs id="EF1" optimise.weights="yes">
    <instance id="F1" optimise.freq="yes"/>
  </equfreqs>

  <siterates id="SR1">
    <instance id="R1" init.value="0.0"/>
    <instance id="R2" init.value="1.0"/>
    <instance id="R3" init.value="1.0"/>
    <instance id="R4" init.value="1.0"/>
    <instance id="R5" init.value="1.0"/>
    <weights id="D1" family="gamma+inv" alpha="0.8" optimise.alpha="yes" pinv="0.4" optimise.pinv="yes">
    </weights>
  </siterates>

  <partitionelem id="partition_elem1" file.name="%s" data.type="nt" interleaved="yes" optimise.weights="yes">
    <mixtureelem list="T1, T1, T1, T1, T1"/>
    <mixtureelem list="M1, M1, M1, M1, M1"/>
    <mixtureelem list="F1, F1, F1, F1, F1"/>
    <mixtureelem list="R1, R2, R3, R4, R5"/>
    <mixtureelem list="L1, L1, L1, L1, L1"/>
  </partitionelem>

</phyml>
',runid,output.file,file.name)
    phyxml
}
```

```{r}
seqdata.fn <- list.files(path="../sequences",pattern="fas",full.names=TRUE)
numsc <- length(seqdata.fn)
seqdata <- list()
for(i in 1:numsc){
    seqdata[[i]] <- read.dna(seqdata.fn[i],format="fasta",as.matrix=TRUE)
}
```

```{r}
stubs <- rep("",numsc)
for(i in 1:numsc){
  stubs[i] <- seqdata.fn[i] %>% strsplit(.,"/") %>% unlist %>% tail(.,1) %>% strsplit(.,".",fixed=TRUE) %>% unlist %>% head(.,1)
}
```

```{r}
for(i in 1:numsc){
  write.dna(seqdata[[i]],paste(stubs[i],".phy",sep=""),format="interleaved")
}
```

```{r}
for(i in 1:numsc){
  phyxml <- phyml.gtr(stubs[i],paste(stubs[i],"_phyml",sep=""),paste(stubs[i],".phy",sep=""))
  cat(phyxml,file=paste(stubs[i],".xml",sep=""),sep="")
}
```

