```{r}
library(ape)
library(magrittr)
library(ggplot2)
```

I load in the clock-like trees generated by LSD.

```{r}
lsd.dirs <- list.dirs("../lsd")
lsd.dirs <- lsd.dirs[2:length(lsd.dirs)]
stubs <- strsplit(lsd.dirs,"/") %>% lapply(.,"[",3) %>% unlist
trees.fn <- paste(lsd.dirs,"/",stubs,"_result_newick_date.txt",sep="")
numtrees <- length(trees.fn)
trees <- list()
for(i in 1:numtrees){
  trees[[i]] <- read.tree(trees.fn[i])
}
```

```{r}
eps <- 0.001
ardfitlist <- list()
symfitlist <- list()
for(i in 1:numtrees){
  print(i)
  tr <- trees[[i]]
  if(!is.binary.tree(tr)){
    tr <- multi2di(tr)
  }
  tr$edge.length <- tr$edge.length+eps
  states<-as.integer(grepl("\\|M\\||\\-MALE",tr$tip.label))
  names(states)<-tr$tip.label
  ardfit <- ace(states,tr,type="discrete",method="ML",model="ARD")
  ardfitlist[[i]] <- ardfit
  symfit <- ace(states,tr,type="discrete",method="ML",model="SYM")
  symfitlist[[i]] <- symfit
}
```

```{r}
svg("mklrt.svg",width=9,height=9)
par(mar=c(20,5,2,1))
ardll <- ardfitlist %>% lapply(.,logLik) %>% unlist
symll <- symfitlist %>% lapply(.,logLik) %>% unlist
barplot(ardll-symll,names=stubs,las=2,ylab="Delta lnL",cex.lab=0.8)
abline(h=2,lty=2)
dev.off()
```


```{r}
malevec <- rep(0,numtrees)
for(i in 1:numtrees){
  tr <- trees[[i]]
  states<-as.integer(grepl("\\|M\\||\\-MALE",tr$tip.label))
  malevec[i] <- table(states)[2]/sum(table(states))
}
```

```{r}
svg("propmales.svg",width=9,height=9)
par(mar=c(20,5,2,1))
barplot(malevec,names=stubs,las=2,ylab="Proportion males",cex.lab=0.8,ylim=c(0.4,0.6),xpd=FALSE)
abline(h=0.5,lty=2)
dev.off()
```

