```{r}
library(ape)
library(magrittr)
```


```{r}
phyml.gtr.partitioned <- function(runid,output.file,file.name1,file.name2,file.name3){
phyxml <- sprintf('
<phyml runid="%s" output.file="%s">

  <topology>
    <instance id="T1" init.tree="bionj" optimise.tree="yes" search="spr"/>
  </topology>

  <branchlengths id="BL1">
    <instance id="L1"/>
    <instance id="L2"/>
    <instance id="L3"/>
  </branchlengths>

  <ratematrices id="RM1">
    <instance id="M1" model="GTR" optimise.rr="yes"/>
    <instance id="M2" model="GTR" optimise.rr="yes"/>
    <instance id="M3" model="GTR" optimise.rr="yes"/>
  </ratematrices>

  <equfreqs id="EF1">
    <instance id="F1" optimise.freqs="yes"/>
    <instance id="F2" optimise.freqs="yes"/>
    <instance id="F3" optimise.freqs="yes"/>
  </equfreqs>

  <siterates id="SR1">
    <instance id="R11" init.value="0.0"/>
    <instance id="R12" init.value="1.0"/>
    <instance id="R13" init.value="1.0"/>
    <instance id="R14" init.value="1.0"/>
    <instance id="R15" init.value="1.0"/>
    <weights id="D11" family="gamma+inv" alpha="0.8" optimise.alpha="yes" pinv="0.4" optimise.pinv="yes">
    </weights>
  </siterates>

  <siterates id="SR2">
    <instance id="R21" init.value="0.0"/>
    <instance id="R22" init.value="1.0"/>
    <instance id="R23" init.value="1.0"/>
    <instance id="R24" init.value="1.0"/>
    <instance id="R25" init.value="1.0"/>
    <weights id="D21" family="gamma+inv" alpha="0.8" optimise.alpha="yes" pinv="0.4" optimise.pinv="yes">
    </weights>
  </siterates>

  <siterates id="SR3">
    <instance id="R31" init.value="0.0"/>
    <instance id="R32" init.value="1.0"/>
    <instance id="R33" init.value="1.0"/>
    <instance id="R34" init.value="1.0"/>
    <instance id="R35" init.value="1.0"/>
    <weights id="D31" family="gamma+inv" alpha="0.8" optimise.alpha="yes" pinv="0.4" optimise.pinv="yes">
    </weights>
  </siterates>

  <partitionelem id="partition1" file.name="%s" data.type="nt" interleaved="yes" optimise.tree.size="yes">
    <mixtureelem list="T1, T1, T1, T1, T1"/>
    <mixtureelem list="M1, M1, M1, M1, M1"/>
    <mixtureelem list="F1, F1, F1, F1, F1"/>
    <mixtureelem list="R11, R12, R13, R14, R15"/>
    <mixtureelem list="L1, L1, L1, L1, L1"/>
  </partitionelem>

   <partitionelem id="partition2" file.name="%s" data.type="nt" interleaved="yes" optimise.tree.size="yes">
    <mixtureelem list="T1, T1, T1, T1, T1"/>
    <mixtureelem list="M2, M2, M2, M2, M2"/>
    <mixtureelem list="F2, F2, F2, F2, F2"/>
    <mixtureelem list="R21, R22, R23, R24, R25"/>
    <mixtureelem list="L1, L1, L1, L1, L1"/>
  </partitionelem>

 <partitionelem id="partition3" file.name="%s" data.type="nt" interleaved="yes" optimise.tree.size="yes">
    <mixtureelem list="T1, T1, T1, T1, T1"/>
    <mixtureelem list="M3, M3, M3, M3, M3"/>
    <mixtureelem list="F3, F3, F3, F3, F3"/>
    <mixtureelem list="R31, R32, R33, R34, R35"/>
    <mixtureelem list="L1, L1, L1, L1, L1"/>
  </partitionelem>

</phyml>
',runid,output.file,file.name1,file.name2,file.name3)
    phyxml
}
```

```{r}
seqdata.fn <- list.files(path="../sequences",pattern="fas",full.names=TRUE)
numsc <- length(seqdata.fn)
seqdata <- list()
for(i in 1:numsc){
    seqdata[[i]] <- read.dna(seqdata.fn[i],format="fasta",as.matrix=TRUE)
}
```

```{r}
stubs <- rep("",numsc)
for(i in 1:numsc){
  stubs[i] <- seqdata.fn[i] %>% strsplit(.,"/") %>% unlist %>% tail(.,1) %>% strsplit(.,".",fixed=TRUE) %>% unlist %>% head(.,1)
}
```

Generate boundaries of gag, pol and env.

```{r}
gag1 <- rep(1,15)
gag2 <- c(rep(1440,3),rep(1479,12))
pol1 <- c(rep(1441,3),rep(1480,12))
pol2 <- c(rep(4284,3),rep(4479,12))
env1 <- c(rep(4285,3),rep(4480,12))
env2 <- c(rep(6807,3),rep(6987,12))
```

```{r}
for(i in 1:numsc){
  write.dna(seqdata[[i]][,gag1[i]:gag2[i]],paste(stubs[i],"_gag.phy",sep=""),format="interleaved")
  write.dna(seqdata[[i]][,pol1[i]:pol2[i]],paste(stubs[i],"_pol.phy",sep=""),format="interleaved")
  write.dna(seqdata[[i]][,env1[i]:env2[i]],paste(stubs[i],"_env.phy",sep=""),format="interleaved")
}
```

```{r}
for(i in 1:numsc){
  phyxml <- phyml.gtr.partitioned(stubs[i],paste(stubs[i],"_phyml",sep=""),paste(stubs[i],"_gag.phy",sep=""),paste(stubs[i],"_pol.phy",sep=""),paste(stubs[i],"_env.phy",sep=""))
  cat(phyxml,file=paste(stubs[i],".xml",sep=""),sep="")
}
```

